# permissions for end users to edit hyperparameters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hyperparameter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: meta-server
    app.kubernetes.io/part-of: meta-server
    app.kubernetes.io/managed-by: kustomize
  name: hyperparameter-editor-role
rules:
- apiGroups:
  - core.datatunerx.io
  resources:
  - hyperparameters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.datatunerx.io
  resources:
  - hyperparameters/status
  verbs:
  - get
