# permissions for end users to view llms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: llm-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: meta-server
    app.kubernetes.io/part-of: meta-server
    app.kubernetes.io/managed-by: kustomize
  name: llm-viewer-role
rules:
- apiGroups:
  - core.datatunerx.io
  resources:
  - llms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.datatunerx.io
  resources:
  - llms/status
  verbs:
  - get
