# permissions for end users to view finetunejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: finetunejob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: meta-server
    app.kubernetes.io/part-of: meta-server
    app.kubernetes.io/managed-by: kustomize
  name: finetunejob-viewer-role
rules:
- apiGroups:
  - finetune.datatunerx.io
  resources:
  - finetunejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - finetune.datatunerx.io
  resources:
  - finetunejobs/status
  verbs:
  - get
