# permissions for end users to edit finetunes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: finetune-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: meta-server
    app.kubernetes.io/part-of: meta-server
    app.kubernetes.io/managed-by: kustomize
  name: finetune-editor-role
rules:
- apiGroups:
  - finetune.datatunerx.io
  resources:
  - finetunes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finetune.datatunerx.io
  resources:
  - finetunes/status
  verbs:
  - get
