apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: finetune-experiment-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: finetune-experiment-controller-role
subjects:
- kind: ServiceAccount
  name: finetune-experiment-controller
  namespace: datatunerx-dev
