apiVersion: core.datatunerx.io/v1beta1
kind: LLM
metadata:
  name: llama2-7b
spec:
  llmMetdata:
    name: Llama-2-7b
    domain:
    - NLP
    tasks:
    - "Text Generation"
    frameworks:
    - PyTorch
    languages:
    - English
    license:
    - "https://ai.meta.com/resources/models-and-libraries/llama-downloads/"
    llmImageConfig:
      image: "harobor.custome.com/llama2-7b:v1"
      path: "/data/llama2-7b"
    computeInfrastructure:
      hardware:
        vRam: 6Gi
        cpu: 4
        memory: 28Gi
