apiVersion: core.datatunerx.io/v1beta1
kind: Hyperparameter
metadata:
  labels:
    app.kubernetes.io/name: hyperparameter
    app.kubernetes.io/instance: hyperparameter-sample
    app.kubernetes.io/part-of: meta-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: meta-server
  name: hyperparameter-sample
spec:
  # TODO(user): Add fields here
