apiVersion: finetune.datatunerx.io/v1beta1
kind: FinetuneJob
metadata:
  name: finetunejob-sample
spec:
  finetune:
    finetuneSpec: 
      llm: llama2-7b
      dataset: example-dataset
      hyperparameter: hyperparameter
      resource:
        limits:
          cpu: 2
          memory: 4Gi
          gpu: "1"
        requests:
          cpu: 2
          memory: 4Gi
          gpu: "1"
  scoringConfig:
    name: scorePlugin-0
  serveConfig:
    nodeSelector: test
