## Append samples of your project ##
resources:
- finetune_v1beta1_finetunejob.yaml
- core_v1beta1_hyperparameter.yaml
- core_v1beta1_llm.yaml
- finetune_v1beta1_finetuneworkflow.yaml
- finetune_v1beta1_finetuneexperiment.yaml
- extension_v1beta1_dataset.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
